# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.character_api import CharacterApi


class TestCharacterApi(unittest.TestCase):
    """CharacterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CharacterApi()

    def tearDown(self) -> None:
        pass

    def test_add_character(self) -> None:
        """Test case for add_character

        Add character.
        """
        pass

    def test_delete_character(self) -> None:
        """Test case for delete_character

        Delete character.
        """
        pass

    def test_get_character(self) -> None:
        """Test case for get_character

        Get character.
        """
        pass

    def test_list_character(self) -> None:
        """Test case for list_character

        List character.
        """
        pass

    def test_update_character(self) -> None:
        """Test case for update_character

        Update character.
        """
        pass


if __name__ == '__main__':
    unittest.main()
