# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.category_api import CategoryApi


class TestCategoryApi(unittest.TestCase):
    """CategoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CategoryApi()

    def tearDown(self) -> None:
        pass

    def test_add_category(self) -> None:
        """Test case for add_category

        Add category.
        """
        pass

    def test_add_category_type(self) -> None:
        """Test case for add_category_type

        Add category type.
        """
        pass

    def test_delete_category(self) -> None:
        """Test case for delete_category

        Delete category.
        """
        pass

    def test_delete_category_type(self) -> None:
        """Test case for delete_category_type

        Delete category type.
        """
        pass

    def test_get_category(self) -> None:
        """Test case for get_category

        Get category.
        """
        pass

    def test_get_category_type(self) -> None:
        """Test case for get_category_type

        Get category type.
        """
        pass

    def test_list_category(self) -> None:
        """Test case for list_category

        List category.
        """
        pass

    def test_list_category_type(self) -> None:
        """Test case for list_category_type

        List category type.
        """
        pass

    def test_update_category(self) -> None:
        """Test case for update_category

        Update category.
        """
        pass

    def test_update_category_type(self) -> None:
        """Test case for update_category_type

        Update category type.
        """
        pass


if __name__ == '__main__':
    unittest.main()
