# coding: utf-8

"""
    ComicKing

    Comic catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.new_magazine import NewMagazine

class TestNewMagazine(unittest.TestCase):
    """NewMagazine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewMagazine:
        """Test NewMagazine
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewMagazine`
        """
        model = NewMagazine()
        if include_optional:
            return NewMagazine(
                code = '',
                name = ''
            )
        else:
            return NewMagazine(
                name = '',
        )
        """

    def testNewMagazine(self):
        """Test NewMagazine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
