# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.new_comic_chapter import NewComicChapter

class TestNewComicChapter(unittest.TestCase):
    """NewComicChapter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewComicChapter:
        """Test NewComicChapter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewComicChapter`
        """
        model = NewComicChapter()
        if include_optional:
            return NewComicChapter(
                number = 1.337,
                version = '',
                released_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                thumbnail_link_website_host = '',
                thumbnail_link_relative_reference = '',
                volume_number = ''
            )
        else:
            return NewComicChapter(
                number = 1.337,
        )
        """

    def testNewComicChapter(self):
        """Test NewComicChapter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
