# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.set_comic_character import SetComicCharacter

class TestSetComicCharacter(unittest.TestCase):
    """SetComicCharacter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetComicCharacter:
        """Test SetComicCharacter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetComicCharacter`
        """
        model = SetComicCharacter()
        if include_optional:
            return SetComicCharacter(
                person_code = '',
                is_main = True
            )
        else:
            return SetComicCharacter(
        )
        """

    def testSetComicCharacter(self):
        """Test SetComicCharacter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
