# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.new_link import NewLink

class TestNewLink(unittest.TestCase):
    """NewLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewLink:
        """Test NewLink
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewLink`
        """
        model = NewLink()
        if include_optional:
            return NewLink(
                website_host = '',
                relative_reference = ''
            )
        else:
            return NewLink(
                website_host = '',
        )
        """

    def testNewLink(self):
        """Test NewLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
