# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.comic_api import ComicApi


class TestComicApi(unittest.TestCase):
    """ComicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComicApi()

    def tearDown(self) -> None:
        pass

    def test_add_comic(self) -> None:
        """Test case for add_comic

        Add comic.
        """
        pass

    def test_add_comic_author(self) -> None:
        """Test case for add_comic_author

        Add comic author.
        """
        pass

    def test_add_comic_author_note(self) -> None:
        """Test case for add_comic_author_note

        Add comic author note.
        """
        pass

    def test_add_comic_author_type(self) -> None:
        """Test case for add_comic_author_type

        Add comic author type.
        """
        pass

    def test_add_comic_category(self) -> None:
        """Test case for add_comic_category

        Add comic category.
        """
        pass

    def test_add_comic_character(self) -> None:
        """Test case for add_comic_character

        Add comic character.
        """
        pass

    def test_add_comic_cover(self) -> None:
        """Test case for add_comic_cover

        Add comic cover.
        """
        pass

    def test_add_comic_external(self) -> None:
        """Test case for add_comic_external

        Add comic external.
        """
        pass

    def test_add_comic_relation(self) -> None:
        """Test case for add_comic_relation

        Add comic relation.
        """
        pass

    def test_add_comic_relation_type(self) -> None:
        """Test case for add_comic_relation_type

        Add comic relation type.
        """
        pass

    def test_add_comic_serialization(self) -> None:
        """Test case for add_comic_serialization

        Add comic serialization.
        """
        pass

    def test_add_comic_synopsis(self) -> None:
        """Test case for add_comic_synopsis

        Add comic synopsis.
        """
        pass

    def test_add_comic_tag(self) -> None:
        """Test case for add_comic_tag

        Add comic tag.
        """
        pass

    def test_add_comic_title(self) -> None:
        """Test case for add_comic_title

        Add comic title.
        """
        pass

    def test_delete_comic(self) -> None:
        """Test case for delete_comic

        Delete comic.
        """
        pass

    def test_delete_comic_author(self) -> None:
        """Test case for delete_comic_author

        Delete comic author.
        """
        pass

    def test_delete_comic_author_note(self) -> None:
        """Test case for delete_comic_author_note

        Delete comic author note.
        """
        pass

    def test_delete_comic_author_type(self) -> None:
        """Test case for delete_comic_author_type

        Delete comic author type.
        """
        pass

    def test_delete_comic_category(self) -> None:
        """Test case for delete_comic_category

        Delete comic category.
        """
        pass

    def test_delete_comic_character(self) -> None:
        """Test case for delete_comic_character

        Delete comic character.
        """
        pass

    def test_delete_comic_cover(self) -> None:
        """Test case for delete_comic_cover

        Delete comic cover.
        """
        pass

    def test_delete_comic_external(self) -> None:
        """Test case for delete_comic_external

        Delete comic external.
        """
        pass

    def test_delete_comic_relation(self) -> None:
        """Test case for delete_comic_relation

        Delete comic relation.
        """
        pass

    def test_delete_comic_relation_type(self) -> None:
        """Test case for delete_comic_relation_type

        Delete comic relation type.
        """
        pass

    def test_delete_comic_serialization(self) -> None:
        """Test case for delete_comic_serialization

        Delete comic serialization.
        """
        pass

    def test_delete_comic_synopsis(self) -> None:
        """Test case for delete_comic_synopsis

        Delete comic synopsis.
        """
        pass

    def test_delete_comic_tag(self) -> None:
        """Test case for delete_comic_tag

        Delete comic tag.
        """
        pass

    def test_delete_comic_title(self) -> None:
        """Test case for delete_comic_title

        Delete comic title.
        """
        pass

    def test_get_comic(self) -> None:
        """Test case for get_comic

        Get comic.
        """
        pass

    def test_get_comic_author(self) -> None:
        """Test case for get_comic_author

        Get comic author.
        """
        pass

    def test_get_comic_author_note(self) -> None:
        """Test case for get_comic_author_note

        Get comic author note.
        """
        pass

    def test_get_comic_author_type(self) -> None:
        """Test case for get_comic_author_type

        Get comic author type.
        """
        pass

    def test_get_comic_category(self) -> None:
        """Test case for get_comic_category

        Get comic category.
        """
        pass

    def test_get_comic_character(self) -> None:
        """Test case for get_comic_character

        Get comic character.
        """
        pass

    def test_get_comic_cover(self) -> None:
        """Test case for get_comic_cover

        Get comic cover.
        """
        pass

    def test_get_comic_external(self) -> None:
        """Test case for get_comic_external

        Get comic external.
        """
        pass

    def test_get_comic_relation(self) -> None:
        """Test case for get_comic_relation

        Get comic relation.
        """
        pass

    def test_get_comic_relation_type(self) -> None:
        """Test case for get_comic_relation_type

        Get comic relation type.
        """
        pass

    def test_get_comic_serialization(self) -> None:
        """Test case for get_comic_serialization

        Get comic serialization.
        """
        pass

    def test_get_comic_synopsis(self) -> None:
        """Test case for get_comic_synopsis

        Get comic synopsis.
        """
        pass

    def test_get_comic_tag(self) -> None:
        """Test case for get_comic_tag

        Get comic tag.
        """
        pass

    def test_get_comic_title(self) -> None:
        """Test case for get_comic_title

        Get comic title.
        """
        pass

    def test_list_comic(self) -> None:
        """Test case for list_comic

        List comic.
        """
        pass

    def test_list_comic_author(self) -> None:
        """Test case for list_comic_author

        List comic author.
        """
        pass

    def test_list_comic_author_note(self) -> None:
        """Test case for list_comic_author_note

        List comic author note.
        """
        pass

    def test_list_comic_author_type(self) -> None:
        """Test case for list_comic_author_type

        List comic author type.
        """
        pass

    def test_list_comic_category(self) -> None:
        """Test case for list_comic_category

        List comic category.
        """
        pass

    def test_list_comic_character(self) -> None:
        """Test case for list_comic_character

        List comic character.
        """
        pass

    def test_list_comic_cover(self) -> None:
        """Test case for list_comic_cover

        List comic cover.
        """
        pass

    def test_list_comic_external(self) -> None:
        """Test case for list_comic_external

        List comic external.
        """
        pass

    def test_list_comic_relation(self) -> None:
        """Test case for list_comic_relation

        List comic relation.
        """
        pass

    def test_list_comic_relation_type(self) -> None:
        """Test case for list_comic_relation_type

        List comic relation type.
        """
        pass

    def test_list_comic_serialization(self) -> None:
        """Test case for list_comic_serialization

        List comic serialization.
        """
        pass

    def test_list_comic_synopsis(self) -> None:
        """Test case for list_comic_synopsis

        List comic synopsis.
        """
        pass

    def test_list_comic_tag(self) -> None:
        """Test case for list_comic_tag

        List comic tag.
        """
        pass

    def test_list_comic_title(self) -> None:
        """Test case for list_comic_title

        List comic title.
        """
        pass

    def test_update_comic(self) -> None:
        """Test case for update_comic

        Update comic.
        """
        pass

    def test_update_comic_author(self) -> None:
        """Test case for update_comic_author

        Update comic author.
        """
        pass

    def test_update_comic_author_note(self) -> None:
        """Test case for update_comic_author_note

        Update comic author note.
        """
        pass

    def test_update_comic_author_type(self) -> None:
        """Test case for update_comic_author_type

        Update comic author type.
        """
        pass

    def test_update_comic_category(self) -> None:
        """Test case for update_comic_category

        Update comic category.
        """
        pass

    def test_update_comic_character(self) -> None:
        """Test case for update_comic_character

        Update comic character.
        """
        pass

    def test_update_comic_cover(self) -> None:
        """Test case for update_comic_cover

        Update comic cover.
        """
        pass

    def test_update_comic_external(self) -> None:
        """Test case for update_comic_external

        Update comic external.
        """
        pass

    def test_update_comic_relation(self) -> None:
        """Test case for update_comic_relation

        Update comic relation.
        """
        pass

    def test_update_comic_relation_type(self) -> None:
        """Test case for update_comic_relation_type

        Update comic relation type.
        """
        pass

    def test_update_comic_serialization(self) -> None:
        """Test case for update_comic_serialization

        Update comic serialization.
        """
        pass

    def test_update_comic_synopsis(self) -> None:
        """Test case for update_comic_synopsis

        Update comic synopsis.
        """
        pass

    def test_update_comic_tag(self) -> None:
        """Test case for update_comic_tag

        Update comic tag.
        """
        pass

    def test_update_comic_title(self) -> None:
        """Test case for update_comic_title

        Update comic title.
        """
        pass


if __name__ == '__main__':
    unittest.main()
