# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.tag_api import TagApi


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagApi()

    def tearDown(self) -> None:
        pass

    def test_add_tag(self) -> None:
        """Test case for add_tag

        Add tag.
        """
        pass

    def test_add_tag_type(self) -> None:
        """Test case for add_tag_type

        Add tag type.
        """
        pass

    def test_delete_tag(self) -> None:
        """Test case for delete_tag

        Delete tag.
        """
        pass

    def test_delete_tag_type(self) -> None:
        """Test case for delete_tag_type

        Delete tag type.
        """
        pass

    def test_get_tag(self) -> None:
        """Test case for get_tag

        Get tag.
        """
        pass

    def test_get_tag_type(self) -> None:
        """Test case for get_tag_type

        Get tag type.
        """
        pass

    def test_list_tag(self) -> None:
        """Test case for list_tag

        List tag.
        """
        pass

    def test_list_tag_type(self) -> None:
        """Test case for list_tag_type

        List tag type.
        """
        pass

    def test_update_tag(self) -> None:
        """Test case for update_tag

        Update tag.
        """
        pass

    def test_update_tag_type(self) -> None:
        """Test case for update_tag_type

        Update tag type.
        """
        pass


if __name__ == '__main__':
    unittest.main()
