# coding: utf-8

"""
    ComicKing

    Comic catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.image_api import ImageApi


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageApi()

    def tearDown(self) -> None:
        pass

    def test_add_image(self) -> None:
        """Test case for add_image

        Add image.
        """
        pass

    def test_delete_image(self) -> None:
        """Test case for delete_image

        Delete image.
        """
        pass

    def test_get_image(self) -> None:
        """Test case for get_image

        Get image.
        """
        pass

    def test_list_image(self) -> None:
        """Test case for list_image

        List image.
        """
        pass

    def test_update_image(self) -> None:
        """Test case for update_image

        Update image.
        """
        pass


if __name__ == '__main__':
    unittest.main()
