# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.language_api import LanguageApi


class TestLanguageApi(unittest.TestCase):
    """LanguageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LanguageApi()

    def tearDown(self) -> None:
        pass

    def test_add_language(self) -> None:
        """Test case for add_language

        Add language.
        """
        pass

    def test_delete_language(self) -> None:
        """Test case for delete_language

        Delete language.
        """
        pass

    def test_get_language(self) -> None:
        """Test case for get_language

        Get language.
        """
        pass

    def test_list_language(self) -> None:
        """Test case for list_language

        List language.
        """
        pass

    def test_update_language(self) -> None:
        """Test case for update_language

        Update language.
        """
        pass


if __name__ == '__main__':
    unittest.main()
