# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.link_api import LinkApi


class TestLinkApi(unittest.TestCase):
    """LinkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinkApi()

    def tearDown(self) -> None:
        pass

    def test_add_link(self) -> None:
        """Test case for add_link

        Add link.
        """
        pass

    def test_delete_link(self) -> None:
        """Test case for delete_link

        Delete link.
        """
        pass

    def test_get_link(self) -> None:
        """Test case for get_link

        Get link.
        """
        pass

    def test_list_link(self) -> None:
        """Test case for list_link

        List link.
        """
        pass

    def test_update_link(self) -> None:
        """Test case for update_link

        Update link.
        """
        pass


if __name__ == '__main__':
    unittest.main()
