# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.comic import Comic

class TestComic(unittest.TestCase):
    """Comic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Comic:
        """Test Comic
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Comic`
        """
        model = Comic()
        if include_optional:
            return Comic(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                code = '',
                published_from = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                published_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_chapter = 56,
                total_volume = 56,
                nsfw = 56,
                nsfl = 56,
                title_count = 56,
                cover_count = 56,
                synopsis_count = 56,
                character_count = 56,
                author_count = 56,
                serialization_count = 56,
                external_count = 56,
                chapter_count = 56,
                volume_count = 56,
                category_count = 56,
                tag_count = 56,
                relation_count = 56
            )
        else:
            return Comic(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                code = '',
                title_count = 56,
                cover_count = 56,
                synopsis_count = 56,
                character_count = 56,
                author_count = 56,
                serialization_count = 56,
                external_count = 56,
                chapter_count = 56,
                volume_count = 56,
                category_count = 56,
                tag_count = 56,
                relation_count = 56,
        )
        """

    def testComic(self):
        """Test Comic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
