# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.website_api import WebsiteApi


class TestWebsiteApi(unittest.TestCase):
    """WebsiteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebsiteApi()

    def tearDown(self) -> None:
        pass

    def test_add_website(self) -> None:
        """Test case for add_website

        Add website.
        """
        pass

    def test_delete_website(self) -> None:
        """Test case for delete_website

        Delete website.
        """
        pass

    def test_get_website(self) -> None:
        """Test case for get_website

        Get website.
        """
        pass

    def test_list_website(self) -> None:
        """Test case for list_website

        List website.
        """
        pass

    def test_update_website(self) -> None:
        """Test case for update_website

        Update website.
        """
        pass


if __name__ == '__main__':
    unittest.main()
