# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.set_comic_category import SetComicCategory

class TestSetComicCategory(unittest.TestCase):
    """SetComicCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetComicCategory:
        """Test SetComicCategory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetComicCategory`
        """
        model = SetComicCategory()
        if include_optional:
            return SetComicCategory(
                category_type_code = '',
                category_code = ''
            )
        else:
            return SetComicCategory(
        )
        """

    def testSetComicCategory(self):
        """Test SetComicCategory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
