# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.set_tag import SetTag

class TestSetTag(unittest.TestCase):
    """SetTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetTag:
        """Test SetTag
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetTag`
        """
        model = SetTag()
        if include_optional:
            return SetTag(
                type_code = '',
                code = '',
                name = '',
                link_website_host = '',
                link_relative_reference = ''
            )
        else:
            return SetTag(
        )
        """

    def testSetTag(self):
        """Test SetTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
