# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.new_comic_external import NewComicExternal

class TestNewComicExternal(unittest.TestCase):
    """NewComicExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewComicExternal:
        """Test NewComicExternal
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewComicExternal`
        """
        model = NewComicExternal()
        if include_optional:
            return NewComicExternal(
                link_website_host = '',
                link_relative_reference = '',
                is_official = True,
                is_community = True
            )
        else:
            return NewComicExternal(
                link_website_host = '',
        )
        """

    def testNewComicExternal(self):
        """Test NewComicExternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
