# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.magazine_api import MagazineApi


class TestMagazineApi(unittest.TestCase):
    """MagazineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MagazineApi()

    def tearDown(self) -> None:
        pass

    def test_add_magazine(self) -> None:
        """Test case for add_magazine

        Add magazine.
        """
        pass

    def test_delete_magazine(self) -> None:
        """Test case for delete_magazine

        Delete magazine.
        """
        pass

    def test_get_magazine(self) -> None:
        """Test case for get_magazine

        Get magazine.
        """
        pass

    def test_list_magazine(self) -> None:
        """Test case for list_magazine

        List magazine.
        """
        pass

    def test_update_magazine(self) -> None:
        """Test case for update_magazine

        Update magazine.
        """
        pass


if __name__ == '__main__':
    unittest.main()
