# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.models.comic_chapter_title import ComicChapterTitle

class TestComicChapterTitle(unittest.TestCase):
    """ComicChapterTitle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComicChapterTitle:
        """Test ComicChapterTitle
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComicChapterTitle`
        """
        model = ComicChapterTitle()
        if include_optional:
            return ComicChapterTitle(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ulid = '',
                language_lang = '',
                content = '',
                is_synonym = True,
                is_latinized = True
            )
        else:
            return ComicChapterTitle(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ulid = '',
                language_lang = '',
                content = '',
        )
        """

    def testComicChapterTitle(self):
        """Test ComicChapterTitle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
