# coding: utf-8

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from comicking_openapi.api.comic_volume_api import ComicVolumeApi


class TestComicVolumeApi(unittest.TestCase):
    """ComicVolumeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComicVolumeApi()

    def tearDown(self) -> None:
        pass

    def test_add_comic_volume(self) -> None:
        """Test case for add_comic_volume

        Add comic volume.
        """
        pass

    def test_add_comic_volume_cover(self) -> None:
        """Test case for add_comic_volume_cover

        Add comic volume cover.
        """
        pass

    def test_add_comic_volume_title(self) -> None:
        """Test case for add_comic_volume_title

        Add comic volume title.
        """
        pass

    def test_delete_comic_volume(self) -> None:
        """Test case for delete_comic_volume

        Delete comic volume.
        """
        pass

    def test_delete_comic_volume_cover(self) -> None:
        """Test case for delete_comic_volume_cover

        Delete comic volume cover.
        """
        pass

    def test_delete_comic_volume_title(self) -> None:
        """Test case for delete_comic_volume_title

        Delete comic volume title.
        """
        pass

    def test_get_comic_volume(self) -> None:
        """Test case for get_comic_volume

        Get comic volume.
        """
        pass

    def test_get_comic_volume_cover(self) -> None:
        """Test case for get_comic_volume_cover

        Get comic volume cover.
        """
        pass

    def test_get_comic_volume_title(self) -> None:
        """Test case for get_comic_volume_title

        Get comic volume title.
        """
        pass

    def test_list_comic_volume(self) -> None:
        """Test case for list_comic_volume

        List comic volume.
        """
        pass

    def test_list_comic_volume_cover(self) -> None:
        """Test case for list_comic_volume_cover

        List comic volume cover.
        """
        pass

    def test_list_comic_volume_title(self) -> None:
        """Test case for list_comic_volume_title

        List comic volume title.
        """
        pass

    def test_update_comic_volume(self) -> None:
        """Test case for update_comic_volume

        Update comic volume.
        """
        pass

    def test_update_comic_volume_cover(self) -> None:
        """Test case for update_comic_volume_cover

        Update volume comic cover.
        """
        pass

    def test_update_comic_volume_title(self) -> None:
        """Test case for update_comic_volume_title

        Update comic volume title.
        """
        pass


if __name__ == '__main__':
    unittest.main()
