# coding: utf-8

"""
    ComicKing

    Comic catalog provider.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NewImage(BaseModel):
    """
    NewImage
    """ # noqa: E501
    alternative_text: Optional[StrictStr] = Field(default=None, alias="alternativeText")
    link_website_host: StrictStr = Field(alias="linkWebsiteHost")
    link_relative_reference: Optional[StrictStr] = Field(default=None, alias="linkRelativeReference")
    __properties: ClassVar[List[str]] = ["alternativeText", "linkWebsiteHost", "linkRelativeReference"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewImage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if alternative_text (nullable) is None
        # and model_fields_set contains the field
        if self.alternative_text is None and "alternative_text" in self.model_fields_set:
            _dict['alternativeText'] = None

        # set to None if link_relative_reference (nullable) is None
        # and model_fields_set contains the field
        if self.link_relative_reference is None and "link_relative_reference" in self.model_fields_set:
            _dict['linkRelativeReference'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewImage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alternativeText": obj.get("alternativeText"),
            "linkWebsiteHost": obj.get("linkWebsiteHost"),
            "linkRelativeReference": obj.get("linkRelativeReference")
        })
        return _obj


