# coding: utf-8

# flake8: noqa

"""
    ComicKing

    PHP Symfony-based comic catalog full-stack.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.1"

# import apis into sdk package
from comicking_openapi.api.category_api import CategoryApi
from comicking_openapi.api.character_api import CharacterApi
from comicking_openapi.api.comic_api import ComicApi
from comicking_openapi.api.comic_chapter_api import ComicChapterApi
from comicking_openapi.api.comic_volume_api import ComicVolumeApi
from comicking_openapi.api.language_api import LanguageApi
from comicking_openapi.api.link_api import LinkApi
from comicking_openapi.api.magazine_api import MagazineApi
from comicking_openapi.api.person_api import PersonApi
from comicking_openapi.api.tag_api import TagApi
from comicking_openapi.api.website_api import WebsiteApi

# import ApiClient
from comicking_openapi.api_response import ApiResponse
from comicking_openapi.api_client import ApiClient
from comicking_openapi.configuration import Configuration
from comicking_openapi.exceptions import OpenApiException
from comicking_openapi.exceptions import ApiTypeError
from comicking_openapi.exceptions import ApiValueError
from comicking_openapi.exceptions import ApiKeyError
from comicking_openapi.exceptions import ApiAttributeError
from comicking_openapi.exceptions import ApiException

# import models into sdk package
from comicking_openapi.models.category import Category
from comicking_openapi.models.character import Character
from comicking_openapi.models.comic import Comic
from comicking_openapi.models.comic_author import ComicAuthor
from comicking_openapi.models.comic_author_note import ComicAuthorNote
from comicking_openapi.models.comic_category import ComicCategory
from comicking_openapi.models.comic_chapter import ComicChapter
from comicking_openapi.models.comic_chapter_title import ComicChapterTitle
from comicking_openapi.models.comic_character import ComicCharacter
from comicking_openapi.models.comic_cover import ComicCover
from comicking_openapi.models.comic_external import ComicExternal
from comicking_openapi.models.comic_relation import ComicRelation
from comicking_openapi.models.comic_serialization import ComicSerialization
from comicking_openapi.models.comic_synopsis import ComicSynopsis
from comicking_openapi.models.comic_tag import ComicTag
from comicking_openapi.models.comic_title import ComicTitle
from comicking_openapi.models.comic_volume import ComicVolume
from comicking_openapi.models.comic_volume_cover import ComicVolumeCover
from comicking_openapi.models.comic_volume_title import ComicVolumeTitle
from comicking_openapi.models.error import Error
from comicking_openapi.models.generic_type import GenericType
from comicking_openapi.models.language import Language
from comicking_openapi.models.link import Link
from comicking_openapi.models.magazine import Magazine
from comicking_openapi.models.new_category import NewCategory
from comicking_openapi.models.new_character import NewCharacter
from comicking_openapi.models.new_comic import NewComic
from comicking_openapi.models.new_comic_author import NewComicAuthor
from comicking_openapi.models.new_comic_author_note import NewComicAuthorNote
from comicking_openapi.models.new_comic_category import NewComicCategory
from comicking_openapi.models.new_comic_chapter import NewComicChapter
from comicking_openapi.models.new_comic_chapter_title import NewComicChapterTitle
from comicking_openapi.models.new_comic_character import NewComicCharacter
from comicking_openapi.models.new_comic_cover import NewComicCover
from comicking_openapi.models.new_comic_external import NewComicExternal
from comicking_openapi.models.new_comic_relation import NewComicRelation
from comicking_openapi.models.new_comic_serialization import NewComicSerialization
from comicking_openapi.models.new_comic_synopsis import NewComicSynopsis
from comicking_openapi.models.new_comic_tag import NewComicTag
from comicking_openapi.models.new_comic_title import NewComicTitle
from comicking_openapi.models.new_comic_volume import NewComicVolume
from comicking_openapi.models.new_comic_volume_cover import NewComicVolumeCover
from comicking_openapi.models.new_comic_volume_title import NewComicVolumeTitle
from comicking_openapi.models.new_generic_type import NewGenericType
from comicking_openapi.models.new_language import NewLanguage
from comicking_openapi.models.new_link import NewLink
from comicking_openapi.models.new_magazine import NewMagazine
from comicking_openapi.models.new_person import NewPerson
from comicking_openapi.models.new_tag import NewTag
from comicking_openapi.models.new_website import NewWebsite
from comicking_openapi.models.person import Person
from comicking_openapi.models.set_category import SetCategory
from comicking_openapi.models.set_character import SetCharacter
from comicking_openapi.models.set_comic import SetComic
from comicking_openapi.models.set_comic_author import SetComicAuthor
from comicking_openapi.models.set_comic_author_note import SetComicAuthorNote
from comicking_openapi.models.set_comic_category import SetComicCategory
from comicking_openapi.models.set_comic_chapter import SetComicChapter
from comicking_openapi.models.set_comic_chapter_title import SetComicChapterTitle
from comicking_openapi.models.set_comic_character import SetComicCharacter
from comicking_openapi.models.set_comic_cover import SetComicCover
from comicking_openapi.models.set_comic_external import SetComicExternal
from comicking_openapi.models.set_comic_relation import SetComicRelation
from comicking_openapi.models.set_comic_serialization import SetComicSerialization
from comicking_openapi.models.set_comic_synopsis import SetComicSynopsis
from comicking_openapi.models.set_comic_tag import SetComicTag
from comicking_openapi.models.set_comic_title import SetComicTitle
from comicking_openapi.models.set_comic_volume import SetComicVolume
from comicking_openapi.models.set_comic_volume_cover import SetComicVolumeCover
from comicking_openapi.models.set_comic_volume_title import SetComicVolumeTitle
from comicking_openapi.models.set_generic_type import SetGenericType
from comicking_openapi.models.set_language import SetLanguage
from comicking_openapi.models.set_link import SetLink
from comicking_openapi.models.set_magazine import SetMagazine
from comicking_openapi.models.set_person import SetPerson
from comicking_openapi.models.set_tag import SetTag
from comicking_openapi.models.set_website import SetWebsite
from comicking_openapi.models.tag import Tag
from comicking_openapi.models.website import Website
